### ISSUE TITLE
Not popping minimum value

### ISSUE THREAD

**Issue by handloomweaver** [ncloudioj/cyheap#1]
In [54]: heap.push({"id":3, "price":0.5})

In [55]: heap.push({"id":3, "price":1.0})

In [56]: heap.push({"id":3, "price":2.5})

In [57]: heap.push({"id":3, "price":2.0})

In [58]: heap.push({"id":3, "price":0.3})

In [59]: heap.pop()
Out[59]: {'id': 3, 'price': 0.5}

In [60]: heap.pop()
Out[60]: {'id': 3, 'price': 1.0}

In [61]: heap.pop()
Out[61]: {'id': 3, 'price': 0.30000001192092896}

In [62]: heap.pop()
Out[62]: {'id': 3, 'price': 2.0}

In [63]: heap.pop()
Out[63]: {'id': 3, 'price': 2.5}

In [64]: heap.pop()

**Comment by ncloudioj** [comment]
Thanks for reporting it.

This heap implementation is known to be broken, it was used mainly to demonstrate how to wrap C libraries into Python extensions via Cython. Will probably fix it in the near future.

If you're looking for a heap module for production, check this out https://github.com/tspurway/hustle/tree/master/deps/maxhash.

**Comment by ncloudioj** [comment]
It's now fixed. Turns out the comparison function was implemented poorly for the floating points arithmetic. The heap implementation(i.e. the C library) has been reviewed again as well, it should be good to use.

Thank you @handloomweaver again for reporting this issue.
